version: "3.5"
services:
  trino:
    ports:
      - "8080:8080"
    image: "trinodb/trino:362"
    volumes:
      - ./docker/trino/etc:/usr/lib/trino/etc:ro
      - ./docker/trino/catalog:/etc/trino/catalog

networks:
  default:
    external:
      name: dbt-net
