version: 2

models:
  - name: drop_customer_orders
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: first_order
        tests:
          - not_null
