default:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: admin
      catalog: memory
      host: trino
      port: 8080
      schema: default
      threads: 1
config:
    send_anonymous_usage_stats: False
