default:
  outputs:
    dbt_presto:
      type: presto
      threads: 4
      host: presto
      port: 8080
      user: presto
      database: memory
      schema: default
  target: dbt_presto
config:
    send_anonymous_usage_stats: False
